name: hackathontemplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Location
  geolocator: ^8.1.1

  # Responsive Design
  flutter_screenutil: ^5.2.0

  # Utilities
  image_picker: ^0.8.4+8

  # Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_core_web: ^1.5.3
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.7

  # State Managment
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  json_annotation: ^4.1.0
  get_it: ^7.2.0
  # Theme
  flex_color_scheme: ^4.2.0
  google_fonts: ^2.2.0
  # Splash
  flutter_native_splash: ^2.0.1+1
  # Widget
  loading_overlay: ^0.3.0
  # Test
  rename: ^2.0.1
  google_sign_in: ^5.2.3
  persistent_bottom_nav_bar: ^4.0.2
  group_button: ^4.2.1
  kartal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint
  lint: ^1.8.2
  # Generator
  build_runner: ^2.1.7
  json_serializable: ^4.1.4
  # Testing
  flutter_launcher_icons: ^0.9.2

flutter:
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#42a5f5"

  assets:
    - assets/
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
