// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvffkdZV3JGnQuXyfYMvyexnE7PRo0Mik',
    appId: '1:934254993849:web:756b6a4f13657c582bd668',
    messagingSenderId: '934254993849',
    projectId: 'dartsiders-e270f',
    authDomain: 'dartsiders-e270f.firebaseapp.com',
    storageBucket: 'dartsiders-e270f.appspot.com',
    measurementId: 'G-1ZGRGJZRVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSK5mIktnaebNICRYiQ1WsgKz0HPp0Uo',
    appId: '1:934254993849:android:e070b731faac42e52bd668',
    messagingSenderId: '934254993849',
    projectId: 'dartsiders-e270f',
    storageBucket: 'dartsiders-e270f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf42TQXI-CvvRV2UAAUwp0tatiPSLse5A',
    appId: '1:934254993849:ios:d4d95129f179b04f2bd668',
    messagingSenderId: '934254993849',
    projectId: 'dartsiders-e270f',
    storageBucket: 'dartsiders-e270f.appspot.com',
    iosClientId: '934254993849-8v25sa0564fllk8alpkqrrobqblp3t2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathontemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf42TQXI-CvvRV2UAAUwp0tatiPSLse5A',
    appId: '1:934254993849:ios:d4d95129f179b04f2bd668',
    messagingSenderId: '934254993849',
    projectId: 'dartsiders-e270f',
    storageBucket: 'dartsiders-e270f.appspot.com',
    iosClientId: '934254993849-8v25sa0564fllk8alpkqrrobqblp3t2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathontemplate',
  );
}
